
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('posts').del()
    .then(function () {
      // Inserts seed entries
      return knex('posts').insert([
        {title: 'Harry Potter', content: "Knausgaard master cleanse gentrify, bicycle rights iceland bitters yuccie pitchfork polaroid four dollar toast edison bulb 90's aesthetic. Butcher air plant waistcoat actually. Austin vexillologist art party butcher disrupt shabby chic ramps bespoke tote bag. Quinoa edison bulb tote bag, taxidermy gentrify fashion axe semiotics VHS. Tilde asymmetrical godard schlitz pickled, butcher 8-bit banh mi farm-to-table occupy viral pork belly iPhone affogato. Vaporware bicycle rights put a bird on it austin, sustainable flannel meh butcher locavore pitchfork fanny pack. Banjo ramps raclette waistcoat kombucha. Master cleanse ennui hell of fap, offal viral green juice chillwave keytar messenger bag kale chips la croix fixie. Celiac flexitarian kickstarter hoodie portland, fap sriracha cold-pressed farm-to-table stumptown everyday carry. Woke jean shorts whatever vegan crucifix farm-to-table semiotics mumblecore sartorial DIY hella green juice.", user_id: 1},
        {title: 'Hobbits', content: "Knausgaard master cleanse gentrify, bicycle rights iceland bitters yuccie pitchfork polaroid four dollar toast edison bulb 90's aesthetic. Butcher air plant waistcoat actually. Austin vexillologist art party butcher disrupt shabby chic ramps bespoke tote bag. Quinoa edison bulb tote bag, taxidermy gentrify fashion axe semiotics VHS. Tilde asymmetrical godard schlitz pickled, butcher 8-bit banh mi farm-to-table occupy viral pork belly iPhone affogato. Vaporware bicycle rights put a bird on it austin, sustainable flannel meh butcher locavore pitchfork fanny pack. Banjo ramps raclette waistcoat kombucha. Master cleanse ennui hell of fap, offal viral green juice chillwave keytar messenger bag kale chips la croix fixie. Celiac flexitarian kickstarter hoodie portland, fap sriracha cold-pressed farm-to-table stumptown everyday carry. Woke jean shorts whatever vegan crucifix farm-to-table semiotics mumblecore sartorial DIY hella green juice.", user_id: 2},
        {title: 'Yikes', content:"Intelligentsia master cleanse mixtape flannel 8-bit trust fund activated charcoal sriracha, pug hoodie whatever. Godard squid tumblr flannel, health goth yuccie humblebrag narwhal 3 wolf moon helvetica. Flexitarian prism fanny pack wolf stumptown. XOXO shabby chic before they sold out, ennui meggings pop-up VHS +1 kitsch air plant craft beer. Cold-pressed banh mi post-ironic kale chips, tattooed trust fund taxidermy chicharrones health goth blog umami try-hard meggings viral. Poke blog waistcoat neutra enamel pin meditation. Cornhole tumeric copper mug flannel jean shorts pug. Master cleanse ennui hell of fap, offal viral green juice chillwave keytar messenger bag kale chips la croix fixie. Celiac flexitarian kickstarter hoodie portland, fap sriracha cold-pressed farm-to-table stumptown everyday carry. Woke jean shorts whatever vegan crucifix farm-to-table semiotics mumblecore sartorial DIY hella green juice.", user_id: 3}
      ]);
    });
};
